#!/bin/bash
echo "Los comandos son los siguientes:"
	echo ""
	echo "arbol:"      
	echo "Muestra de manera gráfica la jerarquía de un directorio que se le especifique al comando. Si al comando no se le específica directorio, el comando se ejecuta sobre el directorio actual"
	echo ""
	echo "ayuda:"       
 	echo "Da información acerca de los comandos y respecto al uso de la Terminal"
	echo ""
	echo "infosis:"
	echo "Muestra información sobre el sistema donde se está ejecutando la termina"
	echo ""
	echo "fecha:"
	echo "Muestra la fecha actual"
	echo ""
	echo "hora:"        
	echo "Muestra la hora actual"
	echo ""
	echo "buscar:"      
	echo "Busca un archivo en específico en un directorio en particular. Recibe dos argumentos: el archivo a buscar y el directorio en donde se va a buscar"
	echo ""
	echo "creditos:"    
	echo "Muestra los créditos de los programadores"
	echo ""
	echo "gato:"        
	echo "Juego para dos de gato"
	echo ""
	echo "ahorcado:"     
	echo "Juego para dos de ahorcado"
	echo ""
	echo "prebeplayer:" 
	echo "Ejecuta un reproductor mp3"
	echo ""
